version: '3'
services:
        web:
                image: cafendback
                build: .
                ports:
                        - "8062:8062"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
